# Generated by Django 4.2.7 on 2023-11-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_profile_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='desription',
            field=models.TextField(default='x', max_length=255),
            preserve_default=False,
        ),
    ]
