# Generated by Django 4.2.7 on 2023-11-26 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill_desription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='desription',
            new_name='description',
        ),
    ]
